### ISSUE TITLE
Faire un schema d'architecture de HDFS

### ISSUE THREAD

**Issue by stebourbi** [sio-ecp/cours-hadoop#6]

**Comment by aslvn** [comment]
![capture](https://cloud.githubusercontent.com/assets/22345940/22762392/5d2a8f76-ee5f-11e6-9b92-4dae4ac9f4ba.PNG)

**Comment by aslvn** [comment]
![capture](https://cloud.githubusercontent.com/assets/22345940/22762421/8925573c-ee5f-11e6-881d-67936dfc747b.PNG)
